[project]
name = "llm-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.84.0",
    "beautifulsoup4>=4.14.3",
    "chromadb>=1.5.1",
    "datasets==3.6.0",
    "feedparser>=6.0.12",
    "gensim>=4.4.0",
    "google-generativeai>=0.8.6",
    "gradio>=6.6.0",
    "ipywidgets>=8.1.8",
    "jupyter-dash>=0.4.2",
    "jupyterlab>=4.5.5",
    "langchain>=1.2.10",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.15",
    "langchain-openai>=1.1.10",
    "langchain-text-splitters>=1.1.1",
    "matplotlib>=3.10.8",
    "modal>=1.3.4",
    "numpy>=2.4.2",
    "ollama>=0.6.1",
    "openai>=2.24.0",
    "pandas>=3.0.1",
    "plotly>=6.5.2",
    "protobuf==3.20.2",
    "psutil>=7.2.2",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "sentence-transformers>=5.2.3",
    "setuptools>=82.0.0",
    "speedtest-cli>=2.1.3",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "transformers>=5.2.0",
    "wandb>=0.25.0",
]
